name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build for ARM64
      run: make compile-arm64

    - name: Build for AMD64
      run: make compile-amd64
